### ISSUE TITLE
Use ActiveData instead of text logs?

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/wptview#37]
ActiveData [1] indexes all tests from all structured logs, including logs for web-platform-tests.  It is accessible via a public service endpoint [2].   Unfortunately, ActiveData only indexes the `subtests` if they fail [3].  Turning on indexing for all `subtests` can be done easily, if required.

Hopefully you find ActiveData to be faster, with more data, and easier to explore.  

[1] http://activedata.allizom.org/tools/query.html
[2] http://activedata.allizom.org/query
[3] http://activedata.allizom.org/tools/query.html#query_id=_bK62zDK

**Comment by jgraham** [comment]
That would make sense if the only goal here was to view runs from Mozilla CI. However there are a couple of other requirements we have, notably the ability to view logs produced in other browsers so that we can do e.g. Gecko vs Blink or Servo vs Gecko comparisons. Since that data isn't in ActiveData we would require the ability to ingest log files directly anyway. Given that, adding AD as a data source seems like extra complexity for little gain at this point.
